### ISSUE TITLE
Create server side testing infrastructure

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/bubble_scan#76]
**Is your feature request related to a problem? Please describe.**
Current server side code has no tests. In order to add tests, a testing infrastructure needs to be added to the project, along with test automation. 

**Describe the solution you'd like**
Pytest is a good framework often used for python testing. It works well with flask applications. Create a ```tests``` directory under the ServerCode directory. Add files with tests for the server side application. For each python file X.py in the ServerCode there should be a test_X.py in the tests code. Test the routes and the machine vision components.

Add a GitHub workflow that will automatically run all tests on each push to the repo.
Here's a sample workflow that AI generated for me, when I asked it to do this work (claude.ai):
```
name: Flask Application Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests with pytest
      run: pytest tests/ --cov=./ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results/
      if: always()
```
